[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Quang Tran <54891109+quangtran2209@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
